version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      - internal
    volumes:
      - ./templates:/etc/nginx/templates
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - mysql
      - php
  php:
    image: php:8-fpm
    build:
      context: ./build
      dockerfile: Dockerfile
    env_file:
      - db.env
    networks:
      - internal
    volumes:
      - ./www:/var/www
      - ./conf/nginx.conf:/usr/local/etc/php-fpm.d/nginx.conf
  mysql:
    image: mysql:latest
    env_file:
      - db.env
    ports:
      - 3306:3306
    networks:
      - internal
networks:
  internal:
    driver: bridge
